### ISSUE TITLE
Q: Custom label

### ISSUE THREAD

**Issue by phun-ky** [jayqi/failed-build-issue-action#118]
Is it possible to add a custom label, instead of `build failed` when a build has failed?

**Comment by jayqi** [comment]
Hi @phun-ky,

I think the `label-name` parameter gets what you need: 

https://github.com/jayqi/failed-build-issue-action/blob/9dcbb15658246bdd43e676bc66313561574ac470/action.yml#L7-L10

I'm going to close this issue because I don't think there is any to-do, but feel free to respond here with any more questions.

**Comment by phun-ky** [comment]
so, like so?

```yaml
…
jobs:
  …
    notify:
      name: Notify failed check
      needs: check
      if: failure()
      runs-on: ubuntu-latest
      steps:
        - uses: jayqi/failed-build-issue-action@v1.2
          with:
            github-token: ${{ secrets.GH_TOKEN }}
            label-name: "new label to be used instead of default"
…
```
